### ISSUE TITLE
[Core] Markdown files for single repo is over 1mb.

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#382]
## Bug Description
Some of our markdown files for the repositories ar well above 1mb and Github will not render them in the browser. This is an issue as this is one of the "core values" this tool brings to the table "Quick and easy way to changes that happened on infra".

## Possible paths to fix the issue
1) Trim down description of automate backout (tool used by the sheriffs) which usually generates very long descriptions. 
- I have tested the length of changeset 111707 from Mozilla-inbound and it's **24323** characters long, excluding the syntax for links and so on. This tool driven backout commit message isn't even one of the biggest we have either!
- I think 24000+ characters is excessive, and we should limit it to 400 characters or less (which is pretty long again), before sending the commit to `replace_bug_with_url()`.

Using this to quickly test description length I was surprised by the results:
```python
import json

with open("../hg_files/mozilla-inbound.json", "r") as file:
    data = json.load(file)


long_descriptions = 0
total_characters = 0
for entry in data:
    try:
        for commit_nr in data.get(entry).get("changeset_commits"):
            if len(data.get(entry).get("changeset_commits").get(commit_nr).get("commit_message")) > 400:
                long_descriptions += 1
                total_characters = total_characters + len(data.get(entry).get("changeset_commits").get(commit_nr).get("commit_message"))
            else:
                pass
    except:
        pass


print(long_descriptions)
print(total_characters)
```
**Results:** 
**796 commit messages** are above **400 characters** and their commit messages have a total of **585816** characters! 
The total number of characters in commit descriptions ignores the ones that are under 400 characters.

2) Split the main repo file in more files (eg: mozilla-inbound.part1.md, mozilla-inbound.part2.md). The challenge here is to realize how to keep in file under 999kb and keep the MD structure intact.

3) Only save the newest changes till we hit 999kb. 

The way I see it, we need to go with a combination of point 1 and point 2 or 3.
@lundjordan Any suggestions here? 

## Progression:

- [x] Implement description trimming #389
- [x] Implement datetime in filename Format: repo-name.YYYYMMDD.md #390
- [x] Implement filesize checks. #391
- [ ] Decide if we should split files or not #392

**Comment by lundjordan** [comment]
yes, 1-3 make sense

I would use a datetime against the filenames. so mozilla-inbound.20190314.md for example.

when you save, you ensure total new filesize is <1mb and. if it's more you start new file. No need to get fancy trying to fit X number of commits in the md until we hit near 1mb. just start a new md file.

**Comment by bccrisan** [comment]
In order to handle this, we need to:
 - Create a function that limits the commit_description content to 400 chars or less (the length needs to be tested, we might modify it in the future)
 - If the commit_description has been shortened, add a "continue reading" message + link to commit (git/hg link)
- split the files that are over 1MB to something way smaller, and to do that we need to:
    - check for the file size
    - split to smaller files
    - add link to the other parts at the end of the first one

**Comment by Akhliskun** [comment]
Updated first comment of the issue with a progress section and created sub-issues as doing all work in here will be a bit too much.
